import { createTheme, createThemeContract } from "@vanilla-extract/css";

export const vars = createThemeContract({
  color: {
    background: null,
    surface: null,
    surfaceSubtle: null,
    surfaceRaised: null,
    // 카드 전용 배경 (surface보다 살짝 띄워진 느낌)
    cardBg: null,
    cardBgHover: null,
    surfaceHover: null,
    textPrimary: null,
    textSecondary: null,
    textTertiary: null,
    textInverse: null,
    textDisabled: null,
    border: null,
    borderStrong: null,
    borderFocus: null,
    // 인터랙티브 채우기(버튼/FAB 배경, 카드 보더)
    actionPrimary: null,
    actionPrimaryHover: null,
    actionPrimarySubtle: null,
    // 브랜드 연한 면 + 포커스 링
    brandSoft: null,
    // 브랜드 텍스트 강조색(금액/제목/활성 탭 등 color 전용)
    brandText: null,
    // 입력 필드
    inputBg: null,
    inputBorder: null,
    inputPlaceholder: null,
    // 결제수단 도메인 색
    payment: {
      cash: null,
      cashSoft: null,
      transfer: null,
      transferSoft: null,
      nine: null,
      nineSoft: null,
    },
    // 상태 색상
    success: null,
    successSoft: null,
    warning: null,
    warningSoft: null,
    warningText: null,
    error: null,
    errorSoft: null,
    // 비활성
    disabled: null,
    disabledBg: null,
    overlay: null,
  },
  space: {
    1: null,
    2: null,
    3: null,
    4: null,
    5: null,
    6: null,
    8: null,
    10: null,
    12: null,
  },
  radius: {
    sm: null,
    md: null,
    lg: null,
    xl: null,
    "2xl": null,
    full: null,
  },
  shadow: {
    card: null,
    raised: null,
    sheet: null,
  },
  font: {
    weight: {
      medium: null,
      semibold: null,
      bold: null,
      extrabold: null,
      heavy: null,
      black: null,
    },
    size: {
      xs: null,
      sm: null,
      base: null,
      md: null,
      lg: null,
      xl: null,
      "2xl": null,
      "3xl": null,
      "4xl": null,
    },
    lineHeight: {
      tight: null,
      normal: null,
      relaxed: null,
    },
  },
});

const shared = {
  space: {
    1: "4px",
    2: "8px",
    3: "12px",
    4: "16px",
    5: "20px",
    6: "24px",
    8: "32px",
    10: "40px",
    12: "48px",
  },
  radius: {
    sm: "4px",
    md: "6px",
    lg: "8px",
    xl: "12px",
    "2xl": "16px",
    full: "999px",
  },
  font: {
    weight: {
      medium: "500",
      semibold: "600",
      bold: "700",
      extrabold: "750",
      heavy: "800",
      black: "850",
    },
    size: {
      xs: "11px",
      sm: "12px",
      base: "13px",
      md: "14px",
      lg: "16px",
      xl: "18px",
      "2xl": "20px",
      "3xl": "24px",
      "4xl": "30px",
    },
    lineHeight: {
      tight: "1.2",
      normal: "1.4",
      relaxed: "1.5",
    },
  },
};

export const lightTheme = createTheme(vars, {
  ...shared,
  color: {
    background: "#F7FAF8",
    surface: "#FFFFFF",
    surfaceSubtle: "#EEF5F1",
    surfaceRaised: "#FFFFFF",
    cardBg: "#F4F9F6",
    cardBgHover: "#EBF4EF",
    surfaceHover: "#E4EDE8",
    textPrimary: "#17211D",
    textSecondary: "#65716B",
    textTertiary: "#97A89F",
    textInverse: "#FFFFFF",
    textDisabled: "#B5C4BC",
    border: "#DCE6E0",
    borderStrong: "#B9C9C0",
    borderFocus: "#078765",
    actionPrimary: "#078765",
    actionPrimaryHover: "#066B51",
    actionPrimarySubtle: "#E6F7F1",
    brandSoft: "#C9F4E3",
    brandText: "#066B51",
    inputBg: "#FFFFFF",
    inputBorder: "#C8D8D0",
    inputPlaceholder: "#A5B8AE",
    payment: {
      cash: "#A75C00",
      cashSoft: "#FEF3E2",
      transfer: "#2563EB",
      transferSoft: "#EFF4FF",
      nine: "#7C3AED",
      nineSoft: "#F3EFFE",
    },
    success: "#066B50",
    successSoft: "#E6F7F1",
    warning: "#D97706",
    warningSoft: "#FFFBEB",
    warningText: "#92400E",
    error: "#C53B32",
    errorSoft: "#FFF0EF",
    disabled: "#B5C4BC",
    disabledBg: "#EEF5F1",
    overlay: "rgba(9, 20, 15, 0.46)",
  },
  shadow: {
    card: "0 2px 8px rgba(28, 57, 45, 0.06)",
    raised: "0 8px 24px rgba(28, 57, 45, 0.08)",
    sheet: "0 -12px 36px rgba(9, 20, 15, 0.16)",
  },
});

export const darkTheme = createTheme(vars, {
  ...shared,
  color: {
    background: "#0D1411",
    surface: "#151D19",
    surfaceSubtle: "#1C2722",
    surfaceRaised: "#202D27",
    cardBg: "#1A2420",
    cardBgHover: "#1F2D28",
    surfaceHover: "#2B3933",
    textPrimary: "#F3F7F5",
    textSecondary: "#A5B3AC",
    textTertiary: "#6B7D75",
    textInverse: "#062A1D",
    textDisabled: "#4A5E55",
    border: "#2B3933",
    borderStrong: "#46584F",
    borderFocus: "#4BD3A2",
    actionPrimary: "#4BD3A2",
    actionPrimaryHover: "#70E0B7",
    actionPrimarySubtle: "#132E23",
    brandSoft: "#183C2F",
    brandText: "#72E1B8",
    inputBg: "#1C2722",
    inputBorder: "#3A4D45",
    inputPlaceholder: "#5A7068",
    payment: {
      cash: "#F0B45B",
      cashSoft: "#2A1F08",
      transfer: "#78A7FF",
      transferSoft: "#0E1A32",
      nine: "#C084FC",
      nineSoft: "#1E1130",
    },
    success: "#4BD3A2",
    successSoft: "#0E2A20",
    warning: "#FBBF24",
    warningSoft: "#231A08",
    warningText: "#FDE68A",
    error: "#FF8C82",
    errorSoft: "#2A100E",
    disabled: "#4A5E55",
    disabledBg: "#1C2722",
    overlay: "rgba(0, 0, 0, 0.68)",
  },
  shadow: {
    card: "0 2px 8px rgba(0, 0, 0, 0.18)",
    raised: "0 8px 24px rgba(0, 0, 0, 0.22)",
    sheet: "0 -12px 36px rgba(0, 0, 0, 0.36)",
  },
});
